### ISSUE TITLE
Quest bug TBC 0.5.9

### ISSUE THREAD

**Issue by MrTssma** [DFortun81/ATT-TBC-Classic#10]
![image](https://user-images.githubusercontent.com/36475330/122290307-46cf4000-cefc-11eb-993c-ee4ff9c36430.png)
id 140
![image](https://user-images.githubusercontent.com/36475330/122290341-5058a800-cefc-11eb-9e97-5a3874de2949.png)
id 103

Can't get achivement's. Quest's have already done.

**Comment by DFortun81** [comment]
So what you see here is that those items granted by the quest can be used for something else. You can refer to the tooltip to show you want you need to do with those items and if you don't want to see things like this, you can turn off "Quest Items".
