### ISSUE TITLE
AllTheThings TBC Classic Weapon Skill Lag

### ISSUE THREAD

**Issue by BloodcoreGothWitch** [DFortun81/ATT-TBC-Classic#11]
I already made a reddit post on that subject, so I'll just copy-paste the problem here:

Every time any weapon skill levels up/gets a point, my game lags for a split second. It's especially bothersome when I am disarmed, since my unarmed skill isn't leveled at all, so it gets a point every time I hit something, and every single time it makes the game lag. I don't have any InputLagFix-like addons installed, when I turned off AllTheThings the lag went away completely.

**Comment by DFortun81** [comment]
This should no longer be a problem now that we refresh skills when you open a profession (any profession) rather than when you get a skill update.
