### ISSUE TITLE
Wrong Profession Specialization Showing

### ISSUE THREAD

**Issue by Wyr3d** [DFortun81/ATT-TBC-Classic#12]
Hey there

ATT shows that my char is Primal Leatherworking - which used to be true - but I switched recently to Dragonscale for TBC.  The add-on does not seem to update this at all, so it keeps showing my char as knowing Primal, and showing Primal patterns I don't have in the side panel, but nothing for the Dragonscale I am now.

Not sure how the add-on decides which specilization a character has, but if it's based of the quest taken initially, this might explain the problem - so I would suggest chaning it to an existing specilization if this is the case. Please note that in TBC players can switch specialization by paying a bribe to their current trainer, and using a book in Tanaris

**Comment by DFortun81** [comment]
I believe I addressed this issue a few months back. Please let me know if it's still a problem.
