### ISSUE TITLE
Blank list in BCC

### ISSUE THREAD

**Issue by Aneko1** [DFortun81/ATT-TBC-Classic#13]
Hello, when I logged into BCC today, a blank list popped up and I received the following error message.

Message: Interface\AddOns\ATT-Classic\ATT-Classic-0.6.1.lua:54: Interface\AddOns\ATT-Classic\ATT-Classic.lua:5802: Usage: local isOnQuest = C_QuestLog.IsOnQuest(questID)
Time: Wed Jun 30 14:10:56 2021
Count: 1
Stack: Interface\AddOns\ATT-Classic\ATT-Classic-0.6.1.lua:54: Interface\AddOns\ATT-Classic\ATT-Classic.lua:5802: Usage: local isOnQuest = C_QuestLog.IsOnQuest(questID)
[string "@Interface\AddOns\ATT-Classic\ATT-Classic.lua"]:54: in function <Interface\AddOns\ATT-Classic\ATT-Classic.lua:52>
[string "@Interface\AddOns\ATT-Classic\src\base.lua"]:33: in function <Interface\AddOns\ATT-Classic\src\base.lua:32>

Locals: self = <table> {
 BaseDifficulty = <table> {
 }
 SetDataMember = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:138
 CreateLootThreshold = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:4995
 SpellNameToSpellID = <table> {
 }
 BaseItemWithFactionID = <table> {
 }
 RecursiveClassAndRaceFilter = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:6431
 PlayCompleteSound = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:452
 GetGroupType = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:3150
 BaseCurrencyClass = <table> {
 }
 BaseItem = <table> {
 }
 FilterItemClass_RequireBinding = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:6365
 ToggleMainList = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:2726
 ItemBindFilter = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:6267
 ShowPopupDialog = <function> defined @Interface\AddOns\ATT-Classic\src\base.lua:81
 BaseItemWithQuestID = <table> {
 }
 IsComplete = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:737
 GetTempDataSubMember = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:199
 PlayerGUIDFromInfo = <table> {
 }
 SearchForField = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:2422
 RaceIndex = 10
 BaseQuestUnit = <table> {
 }
 Class = "WARLOCK"
 asset = <function> defined @Interface\AddOns\ATT-Classic\src\base.lua:10
 CollectibleReputations = true
 ShowPopupDialogWithEditBox = <function> defined @Interface\AddOns\ATT-Classic\src\base.lua:101
 CreateCategory = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:3023
 OpenMiniListForCurrentZone = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:9618
 UpdateSoftReserve = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:3419
 BaseTitle = <table> {
 }
 BaseUnit = <table> {
 }
 CreateDeathClass = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:3881
 CreateNPC = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:5394
 CreateTitle = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:6261
 AccountWideDeaths = true
 FilterItemTrackable = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:6400
 countdown = 1
 GetFactionIDByName = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:4036
 __stack = <table> {
 }
 CacheFlightPathDataForTarget = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:4278
 GetFactionStandingThresholdFromString = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:4055
 events = <table> {
 }
 CreateQuestObjective = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:5843
 CurrentMapID = 476
 ParseSoftReserve = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:3179
 GetProgressTextDefault = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:558
 CollectibleExploration = true
 CollectibleQuests = true
 RequireFactionFilter = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:6381
 CollectiblePVPRanks = true
 CollectibleLoot = true
 AlwaysShowUpdate = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.lua:444
 BaseSoftReserveUnit = <table> {
 }
 print = <function> defined @Interface\AddOns\ATT-Classic\ATT-Classic.l

I have ATT-Classic-v0.6.1-bcc.zip installed.

Thanks

**Comment by DFortun81** [comment]
If someone is able to reproduce this, please let me know.
