### ISSUE TITLE
Simple Scroll quest falsely displays as available.

### ISSUE THREAD

**Issue by HadesSmiles** [DFortun81/ATT-TBC-Classic#14]
The level 1 quest "Simple Scroll" in Deathknell shows as available on my level 70 Orc Warrior, but when talking with the NPC, no quests are available. Some basic research indicates that the quest was removed later in the expansions. Perhaps this wasn't restored  for TBC classic.

Addon version is TBC Classic 0.6.2

Screenshot of ATT tooltip:

![image](https://user-images.githubusercontent.com/34427579/124862998-57675900-df84-11eb-9f53-f1bf9cbf69e8.png)

Screenshot of no quest:

![image](https://user-images.githubusercontent.com/34427579/124863031-63ebb180-df84-11eb-8532-3ff2b2c1449f.png)

Screenshot of mini-map:

![image](https://user-images.githubusercontent.com/34427579/124863067-75cd5480-df84-11eb-8d4a-344ae8323eb6.png)

**Comment by DFortun81** [comment]
The tooltips you see there are actually from Questie, ATT doesn't automatically plot anything for you on the map.
