### ISSUE TITLE
Wanted: Thaelis the Hungerer falsely displays as available.

### ISSUE THREAD

**Issue by HadesSmiles** [DFortun81/ATT-TBC-Classic#15]
Character is level 70 Orc Warrior.

Seems like the quest might be gated for Blood Elves only.

Image of quest showing as available:

![image](https://user-images.githubusercontent.com/34427579/125219756-67887c80-e293-11eb-815d-55764cd6153c.png)

Image of the quest not available for interaction:

![image](https://user-images.githubusercontent.com/34427579/125219816-85ee7800-e293-11eb-8d44-2ec396bd44ad.png)

**Comment by DFortun81** [comment]
This tooltip is also from Questie, our tooltips always have ATT in the string somewhere.
