### ISSUE TITLE
Missing Hunter Pet Abilitys in ATT Database

### ISSUE THREAD

**Issue by Donf4b** [DFortun81/ATT-TBC-Classic#18]
Missing Beißen (Spell ID #27348)
Missing Ducken (Spell ID #27346)
Missing Feueratem (Spell ID #34890)
Missing Feueratem (Spell ID #35324)
Missing Große Ausdauer (Spell ID #27364)
Missing Klaue (Spell ID #27347)
Missing Knurren (Spell ID #27344)
Missing Natürliche Rüstung (Spell ID #27362)
Missing Raumkrümmung (Spell ID #35348)
Missing Schrei (Spell ID #27349)
Missing Skorpidgift (Spell ID #27361)

And the following Spells in the ATT Database seem to habe a false Spell ID:
Feueratem
Große Ausdauer
Natürliche Rüstung

**Comment by gbrage** [comment]
No Problem! I have transfered you to the ATT-Classic repo.

**Comment by DFortun81** [comment]
This appears to be fixed already. All of those spellIDs are currently in the Beast Training file.
