### ISSUE TITLE
[TBC Classic] Quest 10992 not in yet

### ISSUE THREAD

**Issue by Cerby3BR** [DFortun81/ATT-TBC-Classic#21]
![image](https://user-images.githubusercontent.com/54936174/128098881-48224006-3ecc-4633-b491-565e875859eb.png)

This quest, The Hawk's Essence, is part of the druid epic flight form questline.

**Comment by DFortun81** [comment]
This was fixed ages ago. It only appears now if you have Phase 2 for TBC activated.
