### ISSUE TITLE
[Formula: Enchant Weapon - Major Striking] is NOT currently in the game.

### ISSUE THREAD

**Issue by Swiftnezz** [DFortun81/ATT-TBC-Classic#26]
Dear AllTheThings Admins,

I'm an avid WoW enchanter in Retail and Classic, however, for today we are focusing on Classic. In the most current updates there has yet to be an fix or correction with "[Formula: Enchant Weapon - Major Striking]".

Hard to believe no one else has spotted or noticed this but being a collector myself and not being able to reach the 100% would be a little off-setting and defeat the purpose of the addon. 

In relation to my pictures, I'm also missing Surefooted enchant but that's the only one that's actually in game currently that I still need to obtain. "[Formula: Enchant Weapon - Major Striking]" is not available.

Currently in game AllTheThings says "[Formula: Enchant Weapon - Major Striking]" is available from both...

1.) Paulsta'ats in Nagrand :
![Paulsta'ats1](https://user-images.githubusercontent.com/93808525/140595132-b92b67b3-fd90-4083-b114-1b0e88675e18.jpg)
![Paulsta'ats2](https://user-images.githubusercontent.com/93808525/140595133-c6e34a3d-f708-44c4-a43a-d701c9c57d7a.jpg)
![Paulsta'ats3](https://user-images.githubusercontent.com/93808525/140595134-d1853c4e-b2f7-413e-b331-4c95b8d4ca5e.jpg)

2.) Karaaz in Netherstorm :
![Karaaz1](https://user-images.githubusercontent.com/93808525/140595416-28595a03-1c84-409a-94bc-64923b426802.jpg)
![Karaaz2](https://user-images.githubusercontent.com/93808525/140595417-065c4646-b1e5-4717-9705-ee666dd2c4b3.jpg)
![Karaaz3](https://user-images.githubusercontent.com/93808525/140595418-c1372a8d-1915-42c9-a7e6-b00db71f371d.jpg)

I can confirm, after checking many times this phase and last, that this formula is still NOT yet available and may be available at a later phase.

![enchantweaponmajorstriking](https://user-images.githubusercontent.com/93808525/140595445-d919910a-6148-496c-84be-b3759bc9c13c.jpg)

Would suggest to please remove it from the current obtainable collection list within WoW Classics AllTheThings addon.
Much thanks and hope everyone in the office and on the team has a wonderful day, cheers!

Sincerely,
Swiftnezz-Faerlina

**Comment by DFortun81** [comment]
This was fixed with this commit:

Commit: e0c8d44b3c74ccb8bb301c95688770cf373c06ef [e0c8d44]
Parents: 1a89cecda3
Author: Crieve <dylanfortune@live.com>
Date: Saturday, November 20, 2021 11:36:34 AM
Committer: Crieve
Enchant Weapon - Major Striking... Phase 3? Please? Blizzard?
