### ISSUE TITLE
Bloodelf Paladin Level 50 Class Quest is wrong

### ISSUE THREAD

**Issue by zatiala** [DFortun81/ATT-TBC-Classic#28]
On my Bloodelf Paladin, the addon shows the quest "Forging the Mightstone" (id=8418) for Sunken Temple, which is an Alliance Paladin quest. The Horde alternative "Ancient Evil" (id=10593) is not shown.

I think the three prequests to Ancient Evil are also missing. The three alliance prequests are correctly not shown as available.

**Comment by DFortun81** [comment]
This should have been fixed a few months ago.
