### ISSUE TITLE
Several Jewelcrafting Recipes are listed as purchasable but they are not

### ISSUE THREAD

**Issue by Jokaleth** [DFortun81/ATT-TBC-Classic#29]
These 4 Jewelcrafting recipes are listed as obtainable from the Mount Hyjal reputation vendor just inside the entrance to the instance. However after purchasing every recipe from her, they do not appear in her inventory.

![image](https://user-images.githubusercontent.com/87456827/153103120-3f145d8f-b77f-4ff4-ae76-9221f508894f.png)

According to this comment on Wowhead, this may be because they are incorrectly labelled as being for Phase 3 when they should be on Phase 5.

![image](https://user-images.githubusercontent.com/87456827/153103176-dea5bfeb-47b6-4762-bf93-f1eedb76774c.png)

**Comment by Molkree** [comment]
Fixed in 86a58aafe7b1c226dd5569d40d43e62da7d2f279
