### ISSUE TITLE
Purified Shadowsong Amethyst listed as available when it is not

### ISSUE THREAD

**Issue by Jokaleth** [DFortun81/ATT-TBC-Classic#30]
![image](https://user-images.githubusercontent.com/87456827/153960326-fd7dca51-e86c-452e-97ec-0c076578c43a.png)

The Design recipe for Purified Shadowsong Amethyst is only available from being Exalted with the Shattered Sun Offensive reputation which is not available until Sunwell.

https://tbc.wowhead.com/item=37504/design-purified-shadowsong-amethyst

**Comment by DFortun81** [comment]
This appears to have been fixed already. Please let me know if that's not the case.
