### ISSUE TITLE
Heroic access update

### ISSUE THREAD

**Issue by MaximeBrean** [DFortun81/ATT-TBC-Classic#31]
With a recent update on classic TBC, heroic access requirement has changed from revered to honored, using a new set of keys.

Here is old/new keys itemid:
- Hellfire citadel: old=[30622](https://tbc.wowhead.com/item=30622/flamewrought-key), new=[185687](https://tbc.wowhead.com/item=185687/flamewrought-key)
- Coilfang reservoir: old=[30623](https://tbc.wowhead.com/item=30623/reservoir-key), new=[185690](https://tbc.wowhead.com/item=185690/reservoir-key)
- Auchindoun: old=[30633](https://tbc.wowhead.com/item=30633/auchenai-key), new=[185691](https://tbc.wowhead.com/item=185691/auchenai-key)
- Tempest keep: old=[30634](https://tbc.wowhead.com/item=30634/warpforged-key), new=[185692](https://tbc.wowhead.com/item=185692/warpforged-key)
- Cavern of time: old=[30635](https://tbc.wowhead.com/item=30635/key-of-time), new=[185693](https://tbc.wowhead.com/item=185693/key-of-time)

Characters that bought the revered version of the key kept it while the news were added and can't buy the honored version (unless by deleting the old one).

For now, ATT keep listing the old keys and not the new ones. And I don't know if considering the honored version as acquired if the revered version is owned is an easy task, but it would be nice.

**Comment by DFortun81** [comment]
This was updated a while ago. Please let me know if this is still an issue for you.
