### ISSUE TITLE
Quests still show up, even when not selected

### ISSUE THREAD

**Issue by Gogo1951** [DFortun81/ATT-TBC-Classic#33]
I love using ATT for Recipes, and Flight Paths.

But when I turn off Quests, I still see them in the tracker.

![image](https://user-images.githubusercontent.com/55365231/167304038-13651d3e-795b-48cd-ba5b-bc6e0f321657.png)

**Comment by DFortun81** [comment]
This is not a bug, this is intended. You are _on_ those quests.

**Comment by Gogo1951** [comment]
How do I turn quest off all together then?
